theme: jekyll-theme-cayman
title: LeWiDi
description: This is the page of the task 11 @SemEval2023 on Learning with Disagreements Le-Wi-DI, 2nd edition
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
